### ISSUE TITLE
how to reproduce the Quantitative and Qualitative results in paper?

### ISSUE THREAD

**Issue by LongruiDong** [huangjh-pub/di-fusion#10]
Hi~
Thank you for open-sourcing such a fascinating project, I am interested in related research on  implicit scene representation based SLAM. 
I am trying to reproduce some results like Tab .1 & 2 and visualize textured mesh like Fig6 &7 on ICL-nuim and scannet in your paper.
But I have not found relevant codes in the repository

could you share some relevant guidance? @heiwang1997

**Comment by heiwang1997** [comment]
Thanks for your interest!

For qualitative results the config files I used can be retrieved [here](https://drive.google.com/drive/folders/1fWJ02LyEpQ8NqsVJxpkVINAAulmWp9Up?usp=sharing) -- they could be used to reproduce the paper's results.
For scannet which sequence are you referring to?

Best

**Comment by LongruiDong** [comment]
> Thanks for your interest!
> 
> For qualitative results the config files I used can be retrieved [here](https://drive.google.com/drive/folders/1fWJ02LyEpQ8NqsVJxpkVINAAulmWp9Up?usp=sharing) -- they could be used to reproduce the paper's results. For scannet which sequence are you referring to?
> 
> Best

thanks for sharing the config files~

as for scannet, for example scene0000-00?

Actually what I want to know is how to save mesh with textures, currently I can only get voxel grid mesh with uncertainty in visualization window like: (scannet scene0000)
![scannet scene0000](https://user-images.githubusercontent.com/26404032/178148944-ebe6b8a8-4d37-4838-9dea-eca9b62cce3b.png)

**Comment by heiwang1997** [comment]
Hi, we add textures (or more strictly, per-vertex colors) via a post-processing script, using the kNN technique described in our paper. Hence the colors are not directly visible from the viewer.

I've added a new `color` branch with this functionality. You may re-run the reconstruction via `main.py`, and then extract colored mesh via:
```bash
python add_texture.py ../saved/
```

Hope that helps!

**Comment by huangjh-pub** [comment]
Hi, could we assume that you've solved your problem and close the issue? Feel free to reopen it if the problem still exists.

Thanks!
