### ISSUE TITLE
No results in the Displayed Window

### ISSUE THREAD

**Issue by sarwasg** [huangjh-pub/di-fusion#2]
Hello, when I run: 
python main.py configs/fusion-lr-kt.yaml --vis 1
a white window called "Implicit SLAM" is opened but without any content.

**Comment by heiwang1997** [comment]
Hi @sarwasg, could you please press the period key '.' or comma key ',' on your keyboard to see whether it starts to run? This is the shortcut of the GUI as documented in the readme file :)

**Comment by sarwasg** [comment]
> Hi @sarwasg, could you please press the period key '.' or comma key ',' on your keyboard to see whether it starts to run? This is the shortcut of the GUI as documented in the readme file :)
Thanks for the answer. 
Now it works after put '.'. I had to choose a good version of PyTorch. Now I have one Warning from Torch about alogn_corners, but it works. If you can put to the requirement.txt information about the version of all need packages, it will be great.

**Comment by heiwang1997** [comment]
Thanks for pointing this out. We've also noticed that the code will not run on some specific platforms with some versions of pytorch (weird). We will figure this out these days and make the deps files better.

**Comment by trancelestial** [comment]
@sarwasg Have you already successfully generated the dataset? Do you maybe know which installation of flann should be used? (I run Ubuntu 20.04)

**Comment by sarwasg** [comment]
@trancelestial I used flann from this repo: https://github.com/flann-lib/flann My system is Ubuntu 20.04.
