### ISSUE TITLE
Error running PreprocessMeshCUDA (libflann_cuda.so.1.9)

### ISSUE THREAD

**Issue by trancelestial** [huangjh-pub/di-fusion#3]
Hi, great work here!

I've been trying to run the data generation code (copied line generated using data_generator.py which fails): 

`./PreprocessMeshCUDA -m /home/data/ShapeNetCore.v2/04379243/25bc205f6de491f4ccde40b1205ec7ff/models/model_normalized.obj -s 1800000 -o ../di-datasets/shapenet_plivoxs/000598.raw -c ../di-datasets/shapenet_plivoxs/000598.cam -r 1 --surface ../di-datasets/shapenet_plivoxs/000598.surf -p 0.8 --var 0.00015 -e 0.2` 

I keep getting the following error:

`./PreprocessMeshCUDA: error while loading shared libraries: libflann_cuda.so.1.9: cannot open shared object file: No such file or directory`

Note: libflann_cuda.so.1.9 is located in /usr/local/lib

Installing flann was quite a problem. Which flann version/installation method is best used for data generation script to work?

Thank you!

**Comment by heiwang1997** [comment]
Hi @trancelestial, thanks for your interest in our work!
For me, I just installed flann from its original repository. The document is 404 now but you can download a backup [here](https://drive.google.com/file/d/1bhszrRwcTCM-Q4UY2Gxj-vd5lbpjgHvG/view?usp=sharing). Would you please try the following step and tell me which step is causing you the problem so I can diagnose it?

- Clone the [flann](https://github.com/flann-lib/flann) library
- Enable the cuda option in the cmake configuration
- Build and install the flann library.

**Comment by trancelestial** [comment]
Hi @heiwang1997 thanks for your help!
I managed to build flann with cuda and run the data generation code. The main issue during the process (also building Pangolin and its components/requirements s.t. there are no errors produced by PreprocessMeshCUDA) was to get the correct combination of **cmake**, **cuda** and **gcc** versions.

**Comment by hmz-15** [comment]
Hi @trancelestial, I came across exactly the same issue. Would you mind sharing the version of cmake & cuda & gcc that successfully solve the problem? Thanks a lot!

**Comment by hmz-15** [comment]
> Hi @trancelestial, I came across exactly the same issue. Would you mind sharing the version of cmake & cuda & gcc that successfully solve the problem? Thanks a lot!

Solved! Solve the problem with:
`sudo ldconfig -v`
