### ISSUE TITLE
Environmental Configurations Recommendations.

### ISSUE THREAD

**Issue by LiuXinqi12** [huangjh-pub/di-fusion#4]
I have tried different environment configurations and found that there will be problems in some cases. 
The recommended configuration is **python 3.7 + pytorch 1.6 + pytorch_scatter 1.4 + cuda 10.1.**

The following configuration will have some problems, for example
"No module named 'marching_cubes"  or " CUDA error: invalid device ordinal"

The problematic configurations include:
python 3.7 + pytorch 1.7.0 + pytorch_scatter 2.3 + cuda 11.0.
python 3.7 + pytorch 1.7.1 + pytorch_scatter 2.4 + cuda 11.0.
python 3.7 + pytorch 14.0 + pytorch_scatter 1.4 + cuda 10.0.

**Comment by heiwang1997** [comment]
Hi @LiuXinqi12, thank you so much for this exploration! I really appreciate your dedication.
For further information, `CUDA error: invalid device ordinal` is discussed further in [this issue](https://github.com/pytorch/pytorch/issues/52663) here :)
