### ISSUE TITLE
About the scannet training scripts

### ISSUE THREAD

**Issue by chensjtu** [huangjh-pub/di-fusion#5]
Hey! Thanks for your wonderful and impressive work. I'm a newbie in computer graphics and I've tried to use the Di-Fusion to recon the RGBDs in scannet, but I encounter some problems in the data preprocessing. How can you pre-process the images as well as depths in scannet dataset? Many thanks for sharing the data! would you please tell me how to use di-fusion on scannet correctly?

**Comment by watarungurunnn** [comment]
@chensjtu 
Hey! Could you solve this problem? If so, could you send me the script? Thank you.

**Comment by heiwang1997** [comment]
Hi guys, sorry for the late response. For ScanNet we first convert the `sens` files into image and depth sequences using the script from [here](https://github.com/ScanNet/ScanNet/tree/master/SensReader). Then the depth maps are back-projected to point clouds using the intrinsic matrix. The RGB images are used only as post-processing to add textures to the reconstructed meshes.

Could you please share with me more specific problems you've met? I think that will help me better locate where you are struggling with :)

**Comment by huangjh-pub** [comment]
Closed due to inactivity. Feel free to reopen if needed.
